### ISSUE TITLE
Error compiling version R6-10 on ubuntu 18.04

### ISSUE THREAD

**Issue by darcato** [epics-modules/motor#97]
Hi,
I am trying to compile motor R6-10 on Ubuntu 18.04 (g++ version 7.3.0). It stops with error while compiling drvMAXv.cc with many ```invalid conversion from ‘char’ to ‘char*' [-fpermissive]``` errors. In particular in lines: 393, 1267, 1284, 1298.
The problem is due to the call to the following function: ```send_recv_mess(card, "#WS", (char) NULL, q_buf, 1);``` where it expects char* if I'm not wrong. 

The problem seems to be still present on newer commits.

**Comment by keenanlang** [comment]
>NULL is defined to be 0 in C++,

Pre-C++11 it was defined as any macro expression that evaluated to 0, after that point, it is implementation-specific whether it is the literal 0 or a reference to nullptr. Though that doesn't have any effect on this issue.

>IMHO there is no need to cast NULL to anything in these calls

There's no impact on performance, it slightly helps those reading the code, and removes any possible future function overloading ambiguity, I don't really see a compelling reason to remove it. The problem really seems to be that compilers were ever letting this be valid code, though that's likely due to people wanting to keep around C's sloppy type system.
